<?php

/**
 * @file
 * Contains islandora_text_extraction.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;

/**
 * Implements hook_help().
 */
function islandora_text_extraction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_text_extraction module.
    case 'help.page.islandora_text_extraction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Islandora 8 module to connect to Hypercube microservice') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_media_presave().
 */
function islandora_text_extraction_media_presave(MediaInterface $media) {
  if ($media->bundle() != 'extracted_text') {
    return;
  }
  $text = $media->get('field_edited_text')->getValue();
  if (!$text) {
    $file_id = $media->get('field_media_file')->getValue()[0]['target_id'];
    $file = File::load($file_id);
    $data = file_get_contents($file->getFileUri());
    $data = nl2br($data);
    $media->set('field_edited_text', $data);
    $media->field_edited_text->format = 'basic_html';
  }
}

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_text_extraction_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  unset($form['visibility']['ocr_requested']);
  unset($form['visibility']['pdf_text_extraction_requested']);
}
