<?php

namespace Drupal\islandora\Entity;

use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityChangedTrait;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\islandora\FedoraResourceInterface;
use Drupal\user\UserInterface;

/**
 * Defines the Fedora resource entity.
 *
 * @ingroup islandora
 *
 * @ContentEntityType(
 *   id = "fedora_resource",
 *   label = @Translation("Fedora resource"),
 *   bundle_label = @Translation("Fedora resource type"),
 *   handlers = {
 *     "view_builder" = "Drupal\Core\Entity\EntityViewBuilder",
 *     "list_builder" = "Drupal\islandora\FedoraResourceListBuilder",
 *     "views_data" = "Drupal\islandora\Entity\FedoraResourceViewsData",
 *     "inline_form" = "Drupal\islandora\Form\FedoraResourceEntityInlineForm",
 *     "form" = {
 *       "default" = "Drupal\islandora\Form\FedoraResourceForm",
 *       "add" = "Drupal\islandora\Form\FedoraResourceForm",
 *       "edit" = "Drupal\islandora\Form\FedoraResourceForm",
 *       "delete" = "Drupal\islandora\Form\FedoraResourceDeleteForm",
 *     },
 *     "access" = "Drupal\islandora\FedoraResourceAccessControlHandler",
 *     "route_provider" = {
 *       "html" = "Drupal\islandora\FedoraResourceHtmlRouteProvider",
 *     },
 *   },
 *   base_table = "fedora_resource",
 *   data_table = "fedora_resource_field_data",
 *   revision_table = "fedora_resource_revision",
 *   revision_data_table = "fedora_resource_field_data_revision",
 *   translatable = TRUE,
 *   admin_permission = "administer fedora resource entities",
 *   entity_keys = {
 *     "id" = "id",
 *     "revision" = "vid",
 *     "bundle" = "type",
 *     "label" = "name",
 *     "uuid" = "uuid",
 *     "uid" = "user_id",
 *     "langcode" = "langcode",
 *     "status" = "status",
 *   },
 *   common_reference_target = TRUE,
 *   permission_granularity = "bundle",
 *   links = {
 *     "canonical" = "/fedora_resource/{fedora_resource}",
 *     "uuid" = "/islandora_uuid/{fedora_resource}",
 *     "add-form" = "/fedora_resource/add/{fedora_resource_type}",
 *     "edit-form" = "/fedora_resource/{fedora_resource}/edit",
 *     "delete-form" = "/fedora_resource/{fedora_resource}/delete",
 *     "collection" = "/admin/content/fedora_resource",
 *   },
 *   bundle_entity_type = "fedora_resource_type",
 *   field_ui_base_route = "entity.fedora_resource_type.edit_form"
 * )
 */
class FedoraResource extends ContentEntityBase implements FedoraResourceInterface {

  use EntityChangedTrait;

  /**
   * Gets an array of placeholders for Fedora Resource Entity.
   *
   * We are overriding this method to add additional uuid
   * placeholders.
   *
   * @param string $rel
   *   The link relationship type, for example: canonical or edit-form.
   *
   * @return array
   *   An array of URI placeholders.
   */
  protected function urlRouteParameters($rel) {
    // TODO: Change the autogenerated stub.
    $uri_route_parameters = parent::urlRouteParameters($rel);
    if ($rel === 'uuid') {
      $uri_route_parameters[$this->getEntityTypeId()] = $this->uuid();
    }
    return $uri_route_parameters;

  }

  /**
   * {@inheritdoc}
   */
  public static function preCreate(EntityStorageInterface $storage_controller, array &$values) {
    parent::preCreate($storage_controller, $values);
    $values += [
      'user_id' => \Drupal::currentUser()->id(),
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function postSave(EntityStorageInterface $storage, $update = TRUE) {
    parent::postSave($storage, $update);

    // Reindex the entity when it is updated. The entity is automatically
    // indexed when it is added, simply by being added to the {fedora_resource}
    // table. Only required if using the core search index.
    if ($update) {
      if (\Drupal::moduleHandler()->moduleExists('search')) {
        search_mark_for_reindex('fedora_resource_search', $this->id());
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function postDelete(EntityStorageInterface $storage, array $entities) {
    parent::postDelete($storage, $entities);

    // This removes references to deleted parents. But this could be
    // used to remove child entities instead.
    foreach ($entities as $entity) {
      if ($entity->getEntityType()->getBundleEntityType() == 'fedora_resource_type') {
        $references = self::getInboundReferences($entity);
        if ($references) {
          $ref_entities = $storage->loadMultiple($references);
          foreach ($ref_entities as $ref_entity) {
            $ref_entity->removeParent();
            $ref_entity->save();
          }
        }
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getType() {
    return $this->bundle();
  }

  /**
   * {@inheritdoc}
   */
  public function getName() {
    return $this->get('name')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setName($name) {
    $this->set('name', $name);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getCreatedTime() {
    return $this->get('created')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setCreatedTime($timestamp) {
    $this->set('created', $timestamp);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getOwner() {
    return $this->get('user_id')->entity;
  }

  /**
   * {@inheritdoc}
   */
  public function getOwnerId() {
    return $this->get('user_id')->target_id;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwnerId($uid) {
    $this->set('user_id', $uid);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwner(UserInterface $account) {
    $this->set('user_id', $account->id());
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function isPublished() {
    return (bool) $this->getEntityKey('status');
  }

  /**
   * {@inheritdoc}
   */
  public function setPublished($published) {
    $this->set('status', $published ? NODE_PUBLISHED : NODE_NOT_PUBLISHED);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function hasParent() {
    return (!$this->get('fedora_has_parent')->isEmpty());
  }

  /**
   * {@inheritdoc}
   */
  public function getParent() {
    return $this->get('fedora_has_parent')
      ->first()
      ->get('entity')
      ->getTarget()
      ->getValue();
  }

  /**
   * {@inheritdoc}
   */
  public function getParentId() {
    return $this->get('fedora_has_parent')
      ->first()
      ->get('entity')
      ->getTarget()
      ->getValue()
      ->id();
  }

  /**
   * {@inheritdoc}
   */
  public function setParent(FedoraResourceInterface $entity) {
    $this->set('fedora_has_parent', $entity);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function removeParent() {
    $this->set('fedora_has_parent', NULL);
    return $this;
  }

  /**
   * Default value callback for 'fedora_has_parent' base field definition.
   *
   * @see ::baseFieldDefinitions()
   *
   * @return array
   *   An array of default values.
   */
  public static function getFedoraRoot() {
    // Just stub code, we need to figure out what "root is" in this context.
    return NULL;
  }

  /**
   * Get all the objects that have $entity as a fedora_has_parent.
   *
   * @param \Drupal\islandora\FedoraResourceInterface $entity
   *   The entity to find inbound references for.
   *
   * @return array
   *   An array of entity ids
   */
  protected static function getInboundReferences(FedoraResourceInterface $entity) {
    // TODO: Not use static loading.
    $query = \Drupal::entityQuery('fedora_resource');
    $query->condition('fedora_has_parent', $entity->id());
    return $query->execute();
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    $fields['id'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('ID'))
      ->setDescription(t('The ID of the Fedora resource entity.'))
      ->setReadOnly(TRUE);
    $fields['vid'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Revision ID'))
      ->setDescription(t('The Fedora resource revision ID.'))
      ->setReadOnly(TRUE)
      ->setSetting('unsigned', TRUE);
    $fields['type'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Type'))
      ->setDescription(t('The Fedora resource type/bundle.'))
      ->setSetting('target_type', 'fedora_resource_type')
      ->setRequired(TRUE);
    $fields['uuid'] = BaseFieldDefinition::create('uuid')
      ->setLabel(t('UUID'))
      ->setDescription(t('The UUID of the Fedora resource entity.'))
      ->setReadOnly(TRUE);

    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Authored by'))
      ->setDescription(t('The user ID of author of the Fedora resource entity.'))
      ->setRevisionable(TRUE)
      ->setSetting('target_type', 'user')
      ->setSetting('handler', 'default')
      ->setDefaultValueCallback('Drupal\node\Entity\Node::getCurrentUserId')
      ->setTranslatable(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'author',
        'weight' => 0,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 5,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['fedora_has_parent'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Fedora has Parent'))
      ->setDescription(t('Parent Fedora Resource.'))
      ->setRevisionable(TRUE)
      ->setSetting('target_type', 'fedora_resource')
      ->setSetting('handler', 'default')
      ->setDefaultValueCallback('\Drupal\islandora\Entity\FedoraResource::getFedoraRoot')
      ->setTranslatable(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'author',
        'weight' => 0,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 5,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['name'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Name'))
      ->setDescription(t('The name of the Fedora resource entity.'))
      ->setSettings([
        'max_length' => 50,
        'text_processing' => 0,
      ])
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'string',
        'weight' => -4,
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'weight' => -4,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['status'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Publishing status'))
      ->setDescription(t('A boolean indicating whether the Fedora resource is published.'))
      ->setDefaultValue(TRUE);

    $fields['langcode'] = BaseFieldDefinition::create('language')
      ->setLabel(t('Language code'))
      ->setDescription(t('The language code for the Fedora resource entity.'))
      ->setDisplayOptions('form', [
        'type' => 'language_select',
        'weight' => 10,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Created'))
      ->setDescription(t('The time that the entity was created.'));

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the entity was last edited.'));

    $fields['promote'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Promoted to front page'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 15,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['sticky'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Sticky at top of lists'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 16,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['revision_timestamp'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Revision timestamp'))
      ->setDescription(t('The time that the current revision was created.'))
      ->setQueryable(FALSE)
      ->setRevisionable(TRUE);

    $fields['revision_uid'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Revision user ID'))
      ->setDescription(t('The user ID of the author of the current revision.'))
      ->setSetting('target_type', 'user')
      ->setQueryable(FALSE)
      ->setRevisionable(TRUE);

    $fields['revision_log'] = BaseFieldDefinition::create('string_long')
      ->setLabel(t('Revision log message'))
      ->setDescription(t('Briefly describe the changes you have made.'))
      ->setRevisionable(TRUE)
      ->setDefaultValue('')
      ->setDisplayOptions('form', [
        'type' => 'string_textarea',
        'weight' => 25,
        'settings' => [
          'rows' => 4,
        ],
      ]);

    $fields['revision_translation_affected'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Revision translation affected'))
      ->setDescription(t('Indicates if the last edit of a translation belongs to current revision.'))
      ->setReadOnly(TRUE)
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE);
    return $fields;
  }

}
